name: Continuous Deployment to Azure

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Deploy to Azure via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd app/Demo_CI_CD
          
          # 1. Ép Git hủy bỏ mọi thay đổi cục bộ của các file đã có trong repo
          git reset --hard HEAD
          
          # 2. Xóa sạch sành sanh các file rác, file log tự sinh mới (chữ -d là thư mục, -f là file)
          git clean -fd
          
          # 3. Giờ thì kéo code mới về mượt mà không bao giờ bị kẹt nữa
          git pull origin master
          
          # 4. Cấp quyền và kích hoạt deploy script
          chmod +x deploy.sh
          ./deploy.sh </dev/null >/dev/null 2>&1 &
          
          sleep 2
          echo "CD triggered successfully!"  